export const ADD_USER_AS_AUDIENCE = "ADD_USER_AS_AUDIENCE"
export const REMOVE_USER_FROM_AUDIENCE = "REMOVE_USER_FROM_AUDIENCE"
export const SET_LIVE_STREAM_DATA = "SET_LIVE_STREAM_DATA"
export const SET_ACTIVE_LIVE_STREAM = "SET_ACTIVE_LIVE_STREAM"