export const AppConfig = {
  API_URL: process.env.NEXT_PUBLIC_API_URL,
  STREAM_URL: process.env.NEXT_PUBLIC_STREAM_SERVICE,
  MEDIA_SERVER: process.env.NEXT_PUBLIC_MEDIA_SERVER,
  SOCKET_QUEUE: process.env.NEXT_PUBLIC_SOCKET_QUEUE,
};